version: '3.3'

volumes:
  wp:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wp

  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/maria

networks:
  ok:
    driver: bridge

services:
  nginx:
    container_name:
      nginx
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
    networks:
      - ok
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ok
    restart: always
    env_file:
      - .env
    environment:
      ROOT_PASS: ${ROOT_PASS}
      ROOT_USER: ${ROOT_USER}
      NORM_USER: ${NORM_USER}
      NORM_PASS: ${NORM_PASS}
      DB_NAME: ${DB_NAME}
      MYSQL_SOCKET: ${MYSQL_SOCKET}

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    env_file:
      - .env
    environment:
      NORM_USER: ${NORM_USER}
      NORM_PASS: ${NORM_PASS}
      DB_NAME: ${DB_NAME}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - ok
    volumes:
      - wp:/var/www/
    restart: always
# networks:
#   mynetwork:
#     driver: bridge

