version: '3.1'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
#    depends_on:
#      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/ 
    restart: always

#   wordpress:
#     volumes:
#       - wp-volume:/var/www/html/
#     image: wordpress:6.3.0-fpm
#     environment:
#       WP_DEBUG: "true"
#       WP_DEBUG_LOG: php://stdout
#       WORDPRESS_DB_HOST: mariadb
#       WORDPRESS_DB_USER: ${MYSQL_USER}
#       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
#       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
#     networks:
#       - mynetwork
#     restart: always

#   mariadb:
#     image: mariadb
#     environment:
#       MYSQL_ROOT_HOST: '%'
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#     volumes:
#       - mariadb-data:/var/lib/mysql
#     networks:
#       - mynetwork
#     restart: always

# networks:
#   mynetwork:
#     driver: bridge

# volumes:
#   wp-volume:
#   mariadb-data:
