version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports:
      - '443:443'
    # volumes:
    #   - ./wordpress:/var/www/html
    networks:
      - ok
    # depends_on:
    #   - wordpress
    restart: always
  mariadb: 
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - ok
    restart: always


networks:
  ok:
    driver: bridge
