version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports:
      - '443:443'
    volumes:
      - wordpress-files:/var/www/html
    networks:
      - ok
    # depends_on:
    #   - wordpress
    restart: always
  mariadb: 
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - ok
    restart: always


networks:
  ok:
    driver: bridge

volumes:
  wordpress-files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './wordpress_files'
  wordpress-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './wordpress_db'