version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports:
      - '443:443'
    volumes:
      - wp:/var/www/html
    networks:
      - ok
    depends_on:
      - wordpress
    restart: always


networks:
  ok:
    driver: bridge


volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kvebers/data/wordpress'

  maria:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kvebers/data/mariadb'