version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports:
      - '443:443'
    # volumes:
    #   - ./wordpress:/path/inside/container:/var/www/html
    networks:
      - ok
    # depends_on:
    #   - wordpress
    restart: always


networks:
  ok:
    driver: bridge
